#!/bin/sh
set -e

userApiName=handycat/user-api
cardApiName=handycat/card-api
gatewayName=handycat/auth-api


while getopts 'CAacu' OPTION; do
    case "$OPTION" in
        C)mvn clean install -DskipTests
            ;;
        A)docker build -t $cardApiName ./CardApi
          docker build -t $gatewayName ./AuthApi
          docker build -t $userApiName ./UserApi
          docker push $cardApiName
          docker push $gatewayName
          docker push $userApiName
            ;;
        a)docker build -t $gatewayName ./AuthApi
          docker push $gatewayName
            ;;
        c)docker build -t $cardApiName ./CardApi
          docker push $cardApiName
           ;;
        u)docker build -t $userApiName ./UserApi
          docker push $userApiName
            ;;
        ?)echo "Usage: $0 [-C] [-A] [-a] [-c] [-u] "
          exit 1
           ;;
    esac
done


