#!/bin/sh
set -e

userApiName=handycat/user-api
cardApiName=handycat/card-api
gatewayName=handycat/auth-api

version='latest'


while getopts 'dCv:Agcup' OPTION; do
    case "$OPTION" in
        d)docker pull $cardApiName
          docker pull $gatewayName
          docker pull $userApiName
            ;;
        C)mvn clean install -DskipTests
            ;;
        v) version="$OPTARG"
            ;;
        A)docker build -t $cardApiName:"$version" ./CardApi
          docker build -t $gatewayName:"$version" ./AuthApi
          docker build -t $userApiName:"$version" ./UserApi
            ;;
        g)docker build -t $gatewayName:"$version" ./AuthApi
          docker push $gatewayName:"$version"
            ;;
        c)docker build -t $cardApiName:"$version" ./CardApi
          docker push $cardApiName:"$version"
           ;;
        u)docker build -t $userApiName:"$version" ./UserApi
          docker push $userApiName:"$version"
            ;;
        p)docker push $cardApiName:"$version"
          docker push $gatewayName:"$version"
          docker push $userApiName:"$version"
            ;;
        ?)echo "Usage: $0 [-d] [-C] [-A] [-g] [-c] [-u] [-p] "
          exit 1
           ;;
    esac
done


