#!/bin/sh
set -e

userApiName=handycat/user-api
cardApiName=handycat/card-api
gatewayName=handycat/auth-api


while getopts 'dCAgcup' OPTION; do
    case "$OPTION" in
        d)docker pull $cardApiName
          docker pull $gatewayName
          docker pull $userApiName
            ;;
        C)mvn clean install -DskipTests
            ;;
        A)docker build -t $cardApiName ./CardApi
          docker build -t $gatewayName ./AuthApi
          docker build -t $userApiName ./UserApi
            ;;
        g)docker build -t $gatewayName ./AuthApi
          docker push $gatewayName
            ;;
        c)docker build -t $cardApiName ./CardApi
          docker push $cardApiName
           ;;
        u)docker build -t $userApiName ./UserApi
          docker push $userApiName
            ;;
        p)docker push $cardApiName
          docker push $gatewayName
          docker push $userApiName
            ;;
        ?)echo "Usage: $0 [-d] [-C] [-A] [-g] [-c] [-u] [-p] "
          exit 1
           ;;
    esac
done


