version: "3"
services:
  mysqldb:
      image: mysql:latest
      env_file: ./.env
      ports:
        - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_DATABASE: $MYSQL_DATABASE
  webapi:
    depends_on:
      - mysqldb
    restart: on-failure
    image: handycat/web-api-app:latest
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      MYSQL_HOST: mysqldb


