#!/bin/sh
set -e

while getopts 'dm' OPTION; do
    case "$OPTION" in
        d)  docker-compose up
            ;;
        m)  mvn
            ;;
        ?)echo "Usage: $0 [-d]"
          exit 1
           ;;
    esac
dones