#!/bin/sh
set -e

while getopts 'dm' OPTION; do
    case "$OPTION" in
        d)  docker-compose up
            ;;
        m)  mvn -f ./AuthApi/pom.xml spring-boot:run
            mvn -f ./UserApi/pom.xml spring-boot:run
            mvn -f ./CardApi/pom.xml spring-boot:run
            ;;
        ?)echo "Usage: $0 [-d]"
          exit 1
           ;;
    esac
dones