apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqldb
subsets:
  - addresses:
      - ip: 192.168.65.2
    ports:
      - port: 3306