apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calculator-chart.secrets.defaultName" . }}
  labels:
    {{- include "calculator-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.secrets.secret }}
data:
  MYSQL_USER: c3ByaW5ndXNlcg==
  MYSQL_PASSWORD: dTdZSDY1RnJ0NG85
