CREATE TABLE ITEMS
(
    ITEM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID BIGINT UNIQUE NOT NULL,
    ITEM_NAME VARCHAR(40) NOT NULL,
    CREATED_TIMESTAMP DATETIME(6) NULL,
    UPDATED_TIMESTAMP DATETIME(6) NULL
);

CREATE INDEX IDX_CLASS_ID ON ITEMS (CLASS_ID);