CREATE TABLE ITEMS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLASS_ID BIGINT NOT NULL,
    ITEM_NAME VARCHAR(40) NOT NULL,
    CREATED_TIMESTAMP DATETIME(6) NULL,
    UPDATED_TIMESTAMP DATETIME(6) NULL,

    CONSTRAINT U_LOGIN UNIQUE (CLASS_ID)
);

CREATE INDEX IDX_CLASS_ID ON ITEMS (CLASS_ID);